server:
  port: 8084
spring:
  application:
    name: page-server
  thymeleaf:
    cache: false
  rabbitmq:
    host: 39.97.109.245
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}.${server.port}