server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 
ly:
  sms:
    accessKeyId:  # 你自己的accessKeyId
    accessKeySecret: # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_196655016 # 模版CODE