server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 39.97.109.245
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
ly:
  jwt:
    pubKeyPath: F:\\test\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN